/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosECondicoesRouteImport } from './routes/termos-e-condicoes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeEntregaRouteImport } from './routes/politica-de-entrega'
import { Route as PoliticaDeDevolucaoRouteImport } from './routes/politica-de-devolucao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Google4eede3016ec98bdcDothtmlRouteImport } from './routes/google4eede3016ec98bdc[.]html'
import { Route as FloriculturaAbertaAgoraRouteImport } from './routes/floricultura-aberta-agora'
import { Route as Floricultura24hRouteImport } from './routes/floricultura-24h'
import { Route as FloresParaNamoradaRouteImport } from './routes/flores-para-namorada'
import { Route as FloresParaAniversarioRouteImport } from './routes/flores-para-aniversario'
import { Route as EntregaDeFloresHojeRouteImport } from './routes/entrega-de-flores-hoje'
import { Route as DiaDosNamoradosRouteImport } from './routes/dia-dos-namorados'
import { Route as DiaDasMaesRouteImport } from './routes/dia-das-maes'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BuqueDeRosasVermelhasRouteImport } from './routes/buque-de-rosas-vermelhas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as EntregaCidadeRouteImport } from './routes/entrega.$cidade'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminCidadesRouteImport } from './routes/admin.cidades'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'

const TermosECondicoesRoute = TermosECondicoesRouteImport.update({
  id: '/termos-e-condicoes',
  path: '/termos-e-condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeEntregaRoute = PoliticaDeEntregaRouteImport.update({
  id: '/politica-de-entrega',
  path: '/politica-de-entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeDevolucaoRoute = PoliticaDeDevolucaoRouteImport.update({
  id: '/politica-de-devolucao',
  path: '/politica-de-devolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Google4eede3016ec98bdcDothtmlRoute =
  Google4eede3016ec98bdcDothtmlRouteImport.update({
    id: '/google4eede3016ec98bdc.html',
    path: '/google4eede3016ec98bdc.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const FloriculturaAbertaAgoraRoute = FloriculturaAbertaAgoraRouteImport.update({
  id: '/floricultura-aberta-agora',
  path: '/floricultura-aberta-agora',
  getParentRoute: () => rootRouteImport,
} as any)
const Floricultura24hRoute = Floricultura24hRouteImport.update({
  id: '/floricultura-24h',
  path: '/floricultura-24h',
  getParentRoute: () => rootRouteImport,
} as any)
const FloresParaNamoradaRoute = FloresParaNamoradaRouteImport.update({
  id: '/flores-para-namorada',
  path: '/flores-para-namorada',
  getParentRoute: () => rootRouteImport,
} as any)
const FloresParaAniversarioRoute = FloresParaAniversarioRouteImport.update({
  id: '/flores-para-aniversario',
  path: '/flores-para-aniversario',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaDeFloresHojeRoute = EntregaDeFloresHojeRouteImport.update({
  id: '/entrega-de-flores-hoje',
  path: '/entrega-de-flores-hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaDosNamoradosRoute = DiaDosNamoradosRouteImport.update({
  id: '/dia-dos-namorados',
  path: '/dia-dos-namorados',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaDasMaesRoute = DiaDasMaesRouteImport.update({
  id: '/dia-das-maes',
  path: '/dia-das-maes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BuqueDeRosasVermelhasRoute = BuqueDeRosasVermelhasRouteImport.update({
  id: '/buque-de-rosas-vermelhas',
  path: '/buque-de-rosas-vermelhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaCidadeRoute = EntregaCidadeRouteImport.update({
  id: '/entrega/$cidade',
  path: '/entrega/$cidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCidadesRoute = AdminCidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buque-de-rosas-vermelhas': typeof BuqueDeRosasVermelhasRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/dia-das-maes': typeof DiaDasMaesRoute
  '/dia-dos-namorados': typeof DiaDosNamoradosRoute
  '/entrega-de-flores-hoje': typeof EntregaDeFloresHojeRoute
  '/flores-para-aniversario': typeof FloresParaAniversarioRoute
  '/flores-para-namorada': typeof FloresParaNamoradaRoute
  '/floricultura-24h': typeof Floricultura24hRoute
  '/floricultura-aberta-agora': typeof FloriculturaAbertaAgoraRoute
  '/google4eede3016ec98bdc.html': typeof Google4eede3016ec98bdcDothtmlRoute
  '/login': typeof LoginRoute
  '/politica-de-devolucao': typeof PoliticaDeDevolucaoRoute
  '/politica-de-entrega': typeof PoliticaDeEntregaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/entrega/$cidade': typeof EntregaCidadeRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buque-de-rosas-vermelhas': typeof BuqueDeRosasVermelhasRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/dia-das-maes': typeof DiaDasMaesRoute
  '/dia-dos-namorados': typeof DiaDosNamoradosRoute
  '/entrega-de-flores-hoje': typeof EntregaDeFloresHojeRoute
  '/flores-para-aniversario': typeof FloresParaAniversarioRoute
  '/flores-para-namorada': typeof FloresParaNamoradaRoute
  '/floricultura-24h': typeof Floricultura24hRoute
  '/floricultura-aberta-agora': typeof FloriculturaAbertaAgoraRoute
  '/google4eede3016ec98bdc.html': typeof Google4eede3016ec98bdcDothtmlRoute
  '/login': typeof LoginRoute
  '/politica-de-devolucao': typeof PoliticaDeDevolucaoRoute
  '/politica-de-entrega': typeof PoliticaDeEntregaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/entrega/$cidade': typeof EntregaCidadeRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buque-de-rosas-vermelhas': typeof BuqueDeRosasVermelhasRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/dia-das-maes': typeof DiaDasMaesRoute
  '/dia-dos-namorados': typeof DiaDosNamoradosRoute
  '/entrega-de-flores-hoje': typeof EntregaDeFloresHojeRoute
  '/flores-para-aniversario': typeof FloresParaAniversarioRoute
  '/flores-para-namorada': typeof FloresParaNamoradaRoute
  '/floricultura-24h': typeof Floricultura24hRoute
  '/floricultura-aberta-agora': typeof FloriculturaAbertaAgoraRoute
  '/google4eede3016ec98bdc.html': typeof Google4eede3016ec98bdcDothtmlRoute
  '/login': typeof LoginRoute
  '/politica-de-devolucao': typeof PoliticaDeDevolucaoRoute
  '/politica-de-entrega': typeof PoliticaDeEntregaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/entrega/$cidade': typeof EntregaCidadeRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buque-de-rosas-vermelhas'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/dia-das-maes'
    | '/dia-dos-namorados'
    | '/entrega-de-flores-hoje'
    | '/flores-para-aniversario'
    | '/flores-para-namorada'
    | '/floricultura-24h'
    | '/floricultura-aberta-agora'
    | '/google4eede3016ec98bdc.html'
    | '/login'
    | '/politica-de-devolucao'
    | '/politica-de-entrega'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-e-condicoes'
    | '/admin/avaliacoes'
    | '/admin/cidades'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/entrega/$cidade'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buque-de-rosas-vermelhas'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/dia-das-maes'
    | '/dia-dos-namorados'
    | '/entrega-de-flores-hoje'
    | '/flores-para-aniversario'
    | '/flores-para-namorada'
    | '/floricultura-24h'
    | '/floricultura-aberta-agora'
    | '/google4eede3016ec98bdc.html'
    | '/login'
    | '/politica-de-devolucao'
    | '/politica-de-entrega'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-e-condicoes'
    | '/admin/avaliacoes'
    | '/admin/cidades'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/entrega/$cidade'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buque-de-rosas-vermelhas'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/contato'
    | '/dia-das-maes'
    | '/dia-dos-namorados'
    | '/entrega-de-flores-hoje'
    | '/flores-para-aniversario'
    | '/flores-para-namorada'
    | '/floricultura-24h'
    | '/floricultura-aberta-agora'
    | '/google4eede3016ec98bdc.html'
    | '/login'
    | '/politica-de-devolucao'
    | '/politica-de-entrega'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-e-condicoes'
    | '/admin/avaliacoes'
    | '/admin/cidades'
    | '/admin/cupons'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/entrega/$cidade'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuqueDeRosasVermelhasRoute: typeof BuqueDeRosasVermelhasRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  DiaDasMaesRoute: typeof DiaDasMaesRoute
  DiaDosNamoradosRoute: typeof DiaDosNamoradosRoute
  EntregaDeFloresHojeRoute: typeof EntregaDeFloresHojeRoute
  FloresParaAniversarioRoute: typeof FloresParaAniversarioRoute
  FloresParaNamoradaRoute: typeof FloresParaNamoradaRoute
  Floricultura24hRoute: typeof Floricultura24hRoute
  FloriculturaAbertaAgoraRoute: typeof FloriculturaAbertaAgoraRoute
  Google4eede3016ec98bdcDothtmlRoute: typeof Google4eede3016ec98bdcDothtmlRoute
  LoginRoute: typeof LoginRoute
  PoliticaDeDevolucaoRoute: typeof PoliticaDeDevolucaoRoute
  PoliticaDeEntregaRoute: typeof PoliticaDeEntregaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosECondicoesRoute: typeof TermosECondicoesRoute
  EntregaCidadeRoute: typeof EntregaCidadeRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-e-condicoes': {
      id: '/termos-e-condicoes'
      path: '/termos-e-condicoes'
      fullPath: '/termos-e-condicoes'
      preLoaderRoute: typeof TermosECondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-entrega': {
      id: '/politica-de-entrega'
      path: '/politica-de-entrega'
      fullPath: '/politica-de-entrega'
      preLoaderRoute: typeof PoliticaDeEntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-devolucao': {
      id: '/politica-de-devolucao'
      path: '/politica-de-devolucao'
      fullPath: '/politica-de-devolucao'
      preLoaderRoute: typeof PoliticaDeDevolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google4eede3016ec98bdc.html': {
      id: '/google4eede3016ec98bdc.html'
      path: '/google4eede3016ec98bdc.html'
      fullPath: '/google4eede3016ec98bdc.html'
      preLoaderRoute: typeof Google4eede3016ec98bdcDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floricultura-aberta-agora': {
      id: '/floricultura-aberta-agora'
      path: '/floricultura-aberta-agora'
      fullPath: '/floricultura-aberta-agora'
      preLoaderRoute: typeof FloriculturaAbertaAgoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floricultura-24h': {
      id: '/floricultura-24h'
      path: '/floricultura-24h'
      fullPath: '/floricultura-24h'
      preLoaderRoute: typeof Floricultura24hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flores-para-namorada': {
      id: '/flores-para-namorada'
      path: '/flores-para-namorada'
      fullPath: '/flores-para-namorada'
      preLoaderRoute: typeof FloresParaNamoradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flores-para-aniversario': {
      id: '/flores-para-aniversario'
      path: '/flores-para-aniversario'
      fullPath: '/flores-para-aniversario'
      preLoaderRoute: typeof FloresParaAniversarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega-de-flores-hoje': {
      id: '/entrega-de-flores-hoje'
      path: '/entrega-de-flores-hoje'
      fullPath: '/entrega-de-flores-hoje'
      preLoaderRoute: typeof EntregaDeFloresHojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia-dos-namorados': {
      id: '/dia-dos-namorados'
      path: '/dia-dos-namorados'
      fullPath: '/dia-dos-namorados'
      preLoaderRoute: typeof DiaDosNamoradosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia-das-maes': {
      id: '/dia-das-maes'
      path: '/dia-das-maes'
      fullPath: '/dia-das-maes'
      preLoaderRoute: typeof DiaDasMaesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buque-de-rosas-vermelhas': {
      id: '/buque-de-rosas-vermelhas'
      path: '/buque-de-rosas-vermelhas'
      fullPath: '/buque-de-rosas-vermelhas'
      preLoaderRoute: typeof BuqueDeRosasVermelhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega/$cidade': {
      id: '/entrega/$cidade'
      path: '/entrega/$cidade'
      fullPath: '/entrega/$cidade'
      preLoaderRoute: typeof EntregaCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cidades': {
      id: '/admin/cidades'
      path: '/cidades'
      fullPath: '/admin/cidades'
      preLoaderRoute: typeof AdminCidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminCidadesRoute: typeof AdminCidadesRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminCidadesRoute: AdminCidadesRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BuqueDeRosasVermelhasRoute: BuqueDeRosasVermelhasRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  DiaDasMaesRoute: DiaDasMaesRoute,
  DiaDosNamoradosRoute: DiaDosNamoradosRoute,
  EntregaDeFloresHojeRoute: EntregaDeFloresHojeRoute,
  FloresParaAniversarioRoute: FloresParaAniversarioRoute,
  FloresParaNamoradaRoute: FloresParaNamoradaRoute,
  Floricultura24hRoute: Floricultura24hRoute,
  FloriculturaAbertaAgoraRoute: FloriculturaAbertaAgoraRoute,
  Google4eede3016ec98bdcDothtmlRoute: Google4eede3016ec98bdcDothtmlRoute,
  LoginRoute: LoginRoute,
  PoliticaDeDevolucaoRoute: PoliticaDeDevolucaoRoute,
  PoliticaDeEntregaRoute: PoliticaDeEntregaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosECondicoesRoute: TermosECondicoesRoute,
  EntregaCidadeRoute: EntregaCidadeRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
